recipe: default.v1
language: vi

pipeline:
  - name: vietnamese_tokenizer.VietnameseTokenizer
    tokenizer: underthesea
#   - name: WhitespaceTokenizer
  - name: RegexFeaturizer
    number_additional_patterns: 10
  - name: "RegexFeaturizer"
    # Text will be processed with case sensitive as default
    "case_sensitive": True
    # use match word boundaries for lookup table
    "use_word_boundaries": True
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
  - name: RegexEntityExtractor
      # text will be processed with case insensitive as default
    case_sensitive: False
      # use lookup tables to extract entities
    use_lookup_tables: True
      # use regexes to extract entities
    use_regexes: True
      # use match word boundaries for lookup table
    "use_word_boundaries": True
  - name: DucklingEntityExtractor
    dimensions: ["email", "number"]
    url: "http://localhost:8000"
  

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    model_confidence: softmax
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True


